### ISSUE TITLE
Almost zero documentation for the training modules API

### ISSUE THREAD

**Issue by arunchakra** [theislab/ncem#152]
Hello, 

I would like to try out this package but realize there is close to zero documentation in the official 'readthedocs'/API for the train classes. Is this actually the official documentation? None of the parameters are defined, the differences between functions are undefined, and almost nothing is written here. Please correct me if this is not the official documentation. It's unclear how to even use the train modules

https://ncem.readthedocs.io/en/latest/readme.html

**Comment by AnnaChristina** [comment]
Hi @arunchakra, 

we are currently in the process of enhancing our documentation to follow more closely scverse packages so it's easier to use the package. I just released a new readthedocs design and more function information and new tutorials will follow in the upcoming weeks. Please be patient and thanks for your interest in using ncem!

**Comment by j-bac** [comment]
Looking forward! A very simple getting started tutorial from anndata for the current version would be great.
None of the tutorials from ncem_tutorials seem to work for me

I managed to get through [https://github.com/theislab/spatial_scog_workshop_2022/blob/main/ncem/tutorial_ncem.ipynb](https://github.com/theislab/spatial_scog_workshop_2022/blob/main/ncem/tutorial_ncem.ipynb) by fixing several function bugs until getting to function get_sender_receiver_effects

**Comment by zzhu33** [comment]
Any updates? I still can't find more detailed explanations of the parameters in the documentation. This package is very interesting, but it's hard to use properly without more documentation.
